from casual.make.api import *

IncludePaths( ['include',
   '../middleware/common/include',
   '../middleware/serviceframework/include',
   '../middleware/domain/include',
   '../middleware/xatmi/include',
   '../middleware/queue/include',
   '../middleware/buffer/include'] + 
   os.getenv('CASUAL_OPTIONAL_INCLUDE_PATHS').split()
   )

LibraryPaths( [ 'bin',
   '../middleware/xatmi/bin',
   '../middleware/common/bin',
   '../middleware/domain/bin',
   '../middleware/queue/bin',
   '../middleware/buffer/bin',
   '../middleware/transaction/bin',
   '../middleware/serviceframework/bin',
   '../middleware/configuration/bin',
   '../middleware/http/bin'] + 
    os.getenv('CASUAL_OPTIONAL_LIBRARY_PATHS').split()
   )



install_bin = []


# mockup string server
target = LinkExecutable( 'bin/casual-test-mockup-string-server',
   [
      Compile( 'source/mockup/string/server.cpp')
   ],
   ['casual-common', 'casual-xatmi', 'casual-serviceframework'],
)

casual_home = os.getenv('CASUAL_HOME')

Install( [ target], casual_home + '/test/bin')


test_archive = LinkArchive( 'bin/test-archive', 
   [
      Compile( 'source/domain.cpp'),
   ]
)

# unittest

unittest_object = [
   Compile( 'unittest/source/domain/test_basic.cpp'),
   Compile( 'unittest/source/domain/xatmi/test_call.cpp'),
   Compile( 'unittest/source/domain/xatmi/test_conversation.cpp'),
   Compile( 'unittest/source/domain/xatmi/test_start.cpp'),
   Compile( 'unittest/source/domain/test_transaction.cpp'),
]

# only build http test cases if the enviornment is set up
if "CASUAL_UNITTEST_HTTP_INBOUND_CONFIG" in os.environ and "CASUAL_UNITTEST_HTTP_INBOUND_PATH" in os.environ:
   unittest_object.append( Compile( 'unittest/source/domain/test_http.cpp'))

LinkUnittest( 'unittest/bin/test-casual-basic',
   unittest_object,
   [ 
      test_archive,
      'casual-common', 
      #'casual-serviceframework', 
      'casual-buffer',
      'casual-xatmi', 
      'casual-unittest',
      'casual-mockup-rm',
      'casual-domain-unittest'
   ])
	

# Install
Install( install_bin, casual_home + '/bin')


